### PR TITLE
Hardening

### PR DESCRIPTION
**Pull request by TheJoeSchr**
Hi,

I had some troubles with my quite huge spotify library to copy everything at once to gmp, so I had to run copy_all several times. While doing this it made multiple duplicate playlists and I think the reason is because of the cached playlists file so I changed it to get all playlists fresh everytime.

Also there seemed to be a hiccup once with using the logged_in variable between g and s without clearing it once.

The other changes are to not upload the .yaml file with the passwords to git, ignoring files for venv on windows and vscode and changing the logging to info and disable debug so it's not overwhelming/runs faster with regard to my huge library.

This is my first pull request ever, so let me know if I did this right or can do anything else to help. Loved your changes to pyportify!

### CODE REVIEW

**Comment by akatrevorjay** [comment]
Yeah, I had the same issue with multiple playlists, that's what started my patches to this lib :)

**Comment by akatrevorjay** [comment]
I think we can do better with the caching, I've began work to actually _synchronize_ between both services on the fly

**Comment by akatrevorjay** [comment]
Basically I want a service that just keeps both in sync all the time

**Comment by akatrevorjay** [comment]
Unfortunately I'm not too hip on the API mutations that Google's using that you can see in `gmusicapi`'s clients around this. While it's a well done library, it's definitely not simple. You'll notice my absolute hack of using synchronous code in an executor as a workaround for it not being async and my lack of time to get the rest working asynchronously ;)

I think it may be easiest to go that route though until time allows to make that async, it at least allows for not reinventing the wheel here.

**Comment by akatrevorjay** [comment]
Do you mind removing the last commit from this? ie ee33dff . The reason being I'll just remove it in it's entirety, it was only a temporary hack so I could iterate faster on the asyncio lock primitives code, before I put that in I was hitting the API limits every run (since it had no effective limit on the number of concurrent requests as well as no retry).

**Comment by TheJoeSchr** [comment]
Hi,

I also thought along the lines that actually synchronizing would be glad. I wrote a function to delete all empty playlist for example. I also thought a function that merges playlists with the same name would be great. 

I actually didn't touch your async/sync stuff at all, because it seemed to overwhelming without commiting a huge amount of time to properly read/test it. I had once a timeout which broke the whole program, but I then simply removed the playlist with 10k songs in it. 

Can you tell me how I can edit my pull request? I don't seem to be able to remove only the last commit. Maybe you have to close the PR or something first and I have to reenter it?

**Comment by akatrevorjay** [comment]
Sorry I missed this @JoeSchr! Yeah, you just edit the `HEAD` that your pull request is against.

In this case, it's `JoeSchr/pyportify@hardening`, so something like this will work (from git root):

```sh
git co hardening
git branch hardening-backup  # so you have a copy of it still
# Remove one commit from the tip, without modifying workdir contents.
# (You can use more than one '^' as well to do N, or specify a commit hash, etc)
git reset 'HEAD^'
git log  # verify the tip is missing ee33dff
git push -f  # Have to force push since we're removing history
```

That's it! Then you have a local copy of said commits in `hardening-backup`, which you can rename or merge anywhere you want!

Hope this helps!
Trevor

**Comment by akatrevorjay** [comment]
Also, if you're curious about any of the locking and semaphore code I wrote, feel free to send me an email or something. It's straight forward once you know the terminology `asyncio` is using, but, yeah, as I believe you were getting at, there's a *lot* in the `asyncio` docs.

**Comment by TheJoeSchr** [comment]
Hi there,
better late than never! ;)

Thank you very much for your detailed instruction with explanation. I learned much from it!
I did it and pushed it to the hardening branch. Do I need to do anything else now?

**Pull request closed without merging**
